version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: epa
      POSTGRES_PASSWORD: epa
      POSTGRES_DB: epa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro

  app:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://epa:epa@db:5432/epa
      UPLOAD_DIR: /app/data/inbox
      QUARANTINE_DIR: /app/data/quarantine
      LOG_DIR: /app/data/logs
    ports:
      - "8090:8090"
    depends_on:
      - db
    volumes:
      - ./data:/app/data

volumes:
  pgdata:
